CREATE TABLE PARTIDOS(
    NOME CHAR(100) NOT NULL,
    CABECA_LISTA CHAR (100) NOT NULL,
    PRIMARY KEY (NOME));

CREATE TABLE ELEICOES(
    CODIGO INT NOT NULL,
    TIPO CHAR(75) NOT NULL,
    RESULTADO CHAR(75),
    PRIMARY KEY (CODIGO));

CREATE TABLE ELEITORES(
    CC INT NOT NULL,
    NOME CHAR(75) NOT NULL,
    MORADA CHAR(100) NOT NULL,
    FREGUESIA CHAR(75) NOT NULL,
    P_NOME CHAR(100) NOT NULL,
    PRIMARY KEY (CC),
CONSTRAINT NOME
    FOREIGN KEY (P_NOME) REFERENCES PARTIDOS (NOME));

CREATE TABLE PARTIDO_ELEICOES(
    P_NOME CHAR(100) NOT NULL,
    C_CODIGO INT NOT NULL,
    PRIMARY KEY (P_NOME , C_CODIGO),
CONSTRAINT NOME2
    FOREIGN KEY (P_NOME) REFERENCES PARTIDOS (NOME),
CONSTRAINT CODIGO
    FOREIGN KEY (C_CODIGO) REFERENCES ELEICOES (CODIGO));

CREATE TABLE ELEITORES_ELEICOES(
    C_ELEICOES INT NOT NULL,
    CC_ELEITOR INT NOT NULL,
    PRIMARY KEY (C_ELEICOES , CC_ELEITOR),
CONSTRAINT CODIGO2
    FOREIGN KEY (C_ELEICOES) REFERENCES ELEICOES (CODIGO),
CONSTRAINT CC
    FOREIGN KEY (CC_ELEITOR) REFERENCES ELEITORES (CC));
